# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d5346f665debeb4a89d78071a8ea6579fffe6a167471ad399630fa323d8e33567790986076619e92544e563082afda3ca8f73525aa3e82ab9e8db6a7ea2d8fb

test:
  secret_key_base: f5a9a7f33f300723c1b1097a4568a13cdec149ba293f0fa86f09f94389bb3eaf1e682b18d0a95d52f0b9b08cd3067a52fdbcd7af8a3043e421c80aa57140bb01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
